import { createWriteStream } from 'fs';
import { mkdir, unlink } from 'fs/promises';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import PDFDocument from 'pdfkit';
import { createGeminiClient, getGenerativeModelForModelId, DEFAULT_GEMINI_MODEL, GEMINI_KEY_SCOPES } from '../config/geminiConfig.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const UPLOADS_ROOT = join(__dirname, '..', 'uploads');

/**
 * Optional one-line subtitle for the PDF header (Gemini). Empty if API unavailable.
 */
async function fetchMenuTaglineAi(businessName, category, items) {
  const genAI = createGeminiClient(GEMINI_KEY_SCOPES.MERCHANT);
  if (!genAI) return '';
  try {
    const modelId = process.env.GEMINI_MODEL?.trim() || DEFAULT_GEMINI_MODEL;
    const model = getGenerativeModelForModelId(genAI, modelId, {
      generationConfig: { temperature: 0.45, maxOutputTokens: 100 }
    });
    if (!model) return '';
    const sample = items.slice(0, 10).map((i) => i.name).join(', ');
    const prompt = `Business name: "${businessName}". Category: ${category || 'local shop'}.
Sample items on the menu: ${sample}.
Write exactly ONE short subtitle (maximum 14 words) for the top of a printed menu PDF for walk-in customers. Welcoming, no quotes, no emojis, English.`;

    const r = await model.generateContent({
      contents: [{ role: 'user', parts: [{ text: prompt }] }]
    });
    let t = String(r?.response?.text?.() || '').trim();
    t = t.replace(/^["'\s]+|["'\s]+$/g, '').split('\n')[0];
    return t.slice(0, 160);
  } catch (e) {
    console.warn('[menuPdf] Gemini tagline skipped:', e?.message || e);
    return '';
  }
}

function formatPriceInr(n) {
  const x = Number(n);
  if (!Number.isFinite(x)) return '0';
  if (Number.isInteger(x)) return x.toLocaleString('en-IN');
  return x.toLocaleString('en-IN', { minimumFractionDigits: 0, maximumFractionDigits: 2 });
}

export function writeMenuPdfToFile({ businessName, category, menuItems, tagline, filePath }) {
  return mkdir(dirname(filePath), { recursive: true }).then(
    () =>
      new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 52, size: 'A4' });
        const stream = createWriteStream(filePath);
        doc.pipe(stream);

        doc.fillColor('#0f172a').fontSize(22).font('Helvetica-Bold').text(String(businessName || 'Menu'), { align: 'center' });
        doc.moveDown(0.35);
        doc.fontSize(10).font('Helvetica').fillColor('#64748b').text(String(category || 'GoOut merchant').trim() || 'GoOut merchant', { align: 'center' });

        if (tagline) {
          doc.moveDown(0.55);
          doc.fontSize(10).font('Helvetica-Oblique').fillColor('#047857').text(tagline, { align: 'center' });
        }

        doc.moveDown(1.1);
        doc.font('Helvetica-Bold').fontSize(13).fillColor('#0f172a').text('Menu', { underline: true });
        doc.moveDown(0.55);
        doc.font('Helvetica');

        menuItems.forEach((item, idx) => {
          const name = String(item.name || '').trim();
          const priceStr = `Rs. ${formatPriceInr(item.price)}`;
          doc.fontSize(11).fillColor('#0f172a').text(`${idx + 1}. ${name}`, { continued: true });
          doc.fillColor('#059669').text(`  ${priceStr}`);
          if (item.description) {
            doc.moveDown(0.15);
            doc.fontSize(9).fillColor('#64748b').text(`   ${String(item.description).trim()}`, { width: 480 });
          }
          doc.moveDown(0.4);
        });

        doc.moveDown(1.2);
        doc.fontSize(7).fillColor('#94a3b8').font('Helvetica').text('Generated by GoOut · Prices in INR · Check with venue for today’s availability.', {
          align: 'center'
        });

        doc.end();
        stream.on('finish', resolve);
        stream.on('error', reject);
      })
  );
}

/**
 * Writes PDF under uploads/menus/, removes previous AI menu PDF for this business if any.
 * @param {import('mongoose').Document} business - Business with menuItems populated
 * @returns {Promise<{ pdfUrl: string, aiTagline: string }>}
 */
export async function generateAndSaveMenuPdf(business) {
  const items = Array.isArray(business.menuItems) ? business.menuItems : [];
  if (!items.length) throw new Error('No menu items to publish');

  const displayName = String(business.mapDisplayName || business.name || 'Menu').trim() || 'Menu';
  const category = String(business.category || '').trim();

  const aiTagline = await fetchMenuTaglineAi(displayName, category, items);

  const menusDir = join(UPLOADS_ROOT, 'menus');
  await mkdir(menusDir, { recursive: true });
  const filename = `menu-${business._id}-${Date.now()}.pdf`;
  const absPath = join(menusDir, filename);
  const pdfUrl = `/uploads/menus/${filename}`;

  const prev = String(business.menuCatalogFileUrl || '').trim();
  if (prev.startsWith('/uploads/menus/')) {
    const oldAbs = join(UPLOADS_ROOT, prev.replace(/^\/uploads\//, ''));
    unlink(oldAbs).catch(() => {});
  }

  await writeMenuPdfToFile({
    businessName: displayName,
    category,
    menuItems: items,
    tagline: aiTagline,
    filePath: absPath
  });

  return { pdfUrl, aiTagline };
}
